name: Git Hub Actions Demo 
on: push 
jobs:
  Example-Actions-Jobs: 
    name: Exploring Github Actions 
    runs-on: ubuntu-latest
    steps:
      - run: echo "The Job was triggerd by a ${{ githuv.event_name}} event."