name: Git Hub Actions Demo 
on: [push, pull_request, issues] 
jobs:
  Example-Actions-Jobs: 
    name: Exploring Github Actions 
    runs-on: ubuntu-latest
    steps:
      - run: echo "The Job was triggerd by a ${{ github.event_name}} event."

  run-shell-command: 
    runs-on: ubuntu-latest
    needs: Example-Actions-Jobs
    steps:
      - name: update ubuntu
        run: apt get updates 
      - name: check versions 
        run: |
          node -v 
          git -v 