name: Git Hub Actions Demo 
on: [push, pull_request, issues] 
jobs:
  Example-Actions-Jobs: 
    name: Exploring Github Actions 
    runs-on: ubuntu-latest
    steps:
      - run: echo "The Job was triggerd by a ${{ github.event_name}} event."

  run-shell-command: 
    runs-on: ubuntu-latest
    needs: Example-Actions-Jobs
    steps:
      - name: update ubuntu
        run: echo "Hello world"
      - name: check versions 
        run: |
          node -v 
          git -v 
  check-out-files: 
    runs-on: ubuntu-latest
    needs: [Example-Actions-Jobs, run-shell-command]
    steps:
      - name: checkout files
        uses: actions/checkout@v2
      - name: check files
        run: |
          pwd
          ls -a